### ISSUE TITLE
ステージング環境を用意する

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#11]
Vercel上のフロントエンド環境では、PRごとに自動でプレビュー環境ができあがるらしいです。すごい……。
それはさておき、バックエンドではそういうのはないですが、フロントエンドのプレビュー環境に対応した、ステージング環境は必要とのことだったので、こちら用意したいです。

本番環境用のデプロイ設定ができれば、あとはちょろっと、いくつか設定を変えればいいはず……？

**Comment by HaruyaFujimoto** [comment]
> 本番環境用のデプロイ設定ができれば、あとはちょろっと、いくつか設定を変えればいいはず……？

こちら同じ認識です！  

ステージング環境の DB をどうするか考える必要がありそうだと思っています。
PlanetScale にて自分のアカウントで2つ目の DB を作成しようとしたところ、以下のようなメッセージが出てフリープランでは作成できないようでした。
```
You are already using your one free database
Additional Scaler plan databases can be created for $29 each per month.
```

ステージング環境では他のアカウントを使用して PlanetScale の DB を用意することになるでしょうか？
私のアカウントのでもよいのですが、一旦むちょこさんにも相談した方がよさそうでしょうか？

**Comment by HaruyaFujimoto** [comment]
追記です。
PlanetScale ではブランチをわけることでステージング環境用のデータベースなどを扱うことができるのか、  
少し調べてみようと思います。  

感覚的にはブランチはそうゆう使い方じゃない気がしているのですが、どうゆう使い方ができるのか調べてみます。

**Comment by HaruyaFujimoto** [comment]
調べてみたところ、ブランチを作成することで環境ごとに使い分けができるようでした。

- ブランチを作成する
- 作成したブランチにて新しいパスワードを作成する
- アプリケーションの設定にて、新しいブランチで作成したパスワードを設定する
- アプリケーションで特定のブランチに接続できるようになる (rails dbconsole などでテスト)

この方法で問題ないかなと思いましたので、むちょこさんから既にいただいている情報を使って、  
こちらでブランチ作成とパスワード作成ができそうか調べてみようと思います。  
web上のコンソールはこちらでは使えないので、pscale-cl

**Comment by HaruyaFujimoto** [comment]
現時点でむちょこさんから共有していただいている情報では、DB 操作はできるだけで PlanetScale の操作はできないようでした。  
(mysql の接続に使うためのアクセス情報なので当たり前ですが)

PlanetScale のフリープランではメンバーを招待したり Service token を使ったりすることもできないようなので、  
ブランチを作成する方法を取るとしたらむちょこさんに依頼することになりそうです。

**Comment by HAYASHI-Masayuki** [comment]
いろいろ調査ありがとうございます！　こちらはちょっとやっかいそうですね……。
フリープランの次のプランだともう月3000円以上とそこそこのお値段のようですし。

1. 一旦、むちょこさんにお願いして、本番環境用とステージング用でブランチ分けてもらって試してみる。
2. 1で不都合が生じるようなら、私なりふじもとさんなりの方で、ステージング用にアカウント用意して対応することにする。

みたいな感じでしょうか。無料なので仕方ないですが、もうちょっとだけ融通効いたら助かったのですが。
フリープランだと、ブランチもどうも本番環境・開発環境1つずつで2つまで、みたいな感じのようですし。

**Comment by HaruyaFujimoto** [comment]
> フリープランだと、ブランチもどうも本番環境・開発環境1つずつで2つまで、みたいな感じのようですし。

こちら、たしかに料金のところにそう書かれていますね。

https://planetscale.com/docs/concepts/branching#overview
こちらのドキュメントを見てみると、環境ごとにブランチを作るのが公式のやり方だと書かれている様子に見受けられました。
(開発ブランチ1本だけ、という点が特に問題なさそうであればいいのですが。。)

ステージング環境のためにこのブランチを使うというのはよさそだなと感じたのですが、  
本番に反映するたびにコンソールの操作が必要になるので開発のたびにむちょこさんにお願いすることになってしまうと  
ちょっとご負担になるかもなと思いました。

有料プランのメンバー管理のようなものを使わないうちは、  
「共有しても良いフリープランのアカウントを作成してもらってそのログイン情報を共有してもらう」  
みたいなことが可能そうかどうか相談してみるのもいいのかなと思いました。

deploy request などのブランチ管理を毎度お願いしてもよいならそうしますし、  
開発中はバックエンドチーム側でフリープランのアカウントを用意するというやり方も、もしありならそれでもいいのかなと思いました。

**Comment by HAYASHI-Masayuki** [comment]
まだいまいちPlanetScaleのブランチの概念が理解できてません……難しい。
本番環境用のmainブランチから開発用ブランチを切って、スキーマを変更した後デプロイリクエストを作って、mainブランチにマージ、というのが基本的なフローのようですが、これを踏襲せずに直接Railsのマイグレーションで普通にスキーマ変更していくだけ、とかなら権限なくてもできるのかな、とも思ったんですが、ちょっとそこもよくわかりません。

いずれにしても一回むちょこさんに相談するのがいいかもしれませんね。

> 「共有しても良いフリープランのアカウントを作成してもらってそのログイン情報を共有してもらう」

これについては、アカウントを共有するみたいなのは最近の情勢ではあまりよくないと思います。場合によってはある人からはログインできても、ある人からはセキュリティ的なチェックが働いてログインできないような状態になったり、最悪アカウント停止等される可能性もあると思うんですよね。

なので、この辺が妥協点かなと思っています。

> 2. 1で不都合が生じるようなら、私なりふじもとさんなりの方で、ステージング用にアカウント用意して対応することにする。

**Comment by HaruyaFujimoto** [comment]
> まだいまいちPlanetScaleのブランチの概念が理解できてません……難しい。

私もまだまだちゃんとわかっていないです。。  
とりあえず触ってみたところ、

> これを踏襲せずに直接Railsのマイグレーションで普通にスキーマ変更していくだけ

こちらについて、前提として本番ブランチにてスキーマ変更をする際は deploy request を必ず作成する必要があるようです。  
(= 必ず、ウェブ上での操作もしくは cli でのログインが必要)  

フリープランで作成できるブランチが本番・開発がそれぞれ1つずつと書かれていたのですが、  
試したところ本番ブランチも開発ブランチに格下げすることができ、本番ブランチ0・開発ブランチ2という状況も作れるようです。  
(そもそも最初からある main ブランチは初期状態では開発ブランチで、そこからもう一つ開発ブランチを切ることができました)

本番ブランチ0・開発ブランチ2という状況ですと、それぞれのブランチにて Rails のマイグレーション機能を使って自由にスキーマを変更することができるようです。  

---

ちょっと調べた感じでの私見ですが、今の所こんな感じかなという感想です。(間違いがあるかもしれません。。)

- ブランチというのは MySQL でいう別々のデータベースと考えてよさそう (かなり私見)
- ブランチが作成される (分かれる) ときは、元となるデータベースのスキーマだけがコピーされた新しいデータベースが作成されるような感じ (有料プランだと beta 版機能としてデータも複製できるっぽい)
- 作成されたブランチ (データベース) は初期状態で開発ブランチとなりスキーマ編集が自由にできる
- 開発ブランチ・本番ブランチというのは、データベースに与えるロールのようなもの (私見)
- 開発ブランチは本番ブランチに昇格でき、本番ブランチは開発ブランチに降格できる (最初からある main ブランチも初期状態は開発ブランチ)
- 本番ブランチというのは、そのデータベースの可用性を自動で強めてくれるロールのようなもの (レプリカを追加したり自動バックアップ機能を持ったりする)
- 本番ブランチは可用性が強くなってる分、スキーマ変更が deploy request でしか実行できないようになっている (本番ブランチを運用する際には、開発チームがアカウントにログインするか有料のメンバー管理機能が必要そう)
- 本番ブランチが開発ブランチに降格すると、自動バックアップも止まりレプリカもなくなる (高可用性のための機能がなくなる、スキーマ変更は自由にできるようになる)

---

> アカウントを共有するみたいなのは最近の情勢ではあまりよくないと思います。

こちらは私もそう思います。。  
自分で書いていて root アカウントを共有するみたいでどうかなと思ったのですが、(林さんのご指摘には別の懸念点も)  
スキーマ変更がたびたび起こるであろう開発初期段階ではバックエンドチームの誰かがウェブ上の操作ができた方がいいよな、  
と思ってのことでした。

しかし本番ブランチに昇格させなければスキーマ変更もできそうだと少し調べて思ったので、  
ウェブ上の操作はできなくても進められそうだという考えになりました。
ですので、

> 2. 1で不都合が生じるようなら、私なりふじもとさんなりの方で、ステージング用にアカウント用意して対応することにする。

こちらも現状では不要かなという考えになりました。  
本番ブランチを使用する必要性が出てくるとどうしてもアカウントへのログインやメンバーとしてのアクセス権限などが必要になってくると思っているのですが、  
初期開発時点では本番環境も検証環境も開発ブランチを使用してよいのではないかと  
今の所思っています。

というところで、現状の私だけの考えとして以下をむちょこさんに依頼してみようかと思っているのですが、いかがでしょうか？

- Branches > New branch からブランチを作成する (ブランチ名: staging)
- 作成したブランチにて Connect からユーザー名・パスワードを取得する

PlanetScale の仕様について自分の認識だけでのご提案ですので、前提など間違っていたらすいません。  
お手すきの際にご確認をお願いできればと思います。

**Comment by HAYASHI-Masayuki** [comment]
詳しいご説明ありがとうございます！　本番・開発ブランチそれぞれの詳しい挙動など、特に助かりました。

> というところで、現状の私だけの考えとして以下をむちょこさんに依頼してみようかと思っているのですが、いかがでしょうか？

いいと思います！　現状の認識の範囲では、しばらくは開発ブランチだけで回す、という形が確かにベストだと思うので、であればこの流れで進めるのがよさそうです。
こちらお願いします。

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
おはやいご確認ありがとうございました！

@muchoco-dev 
おつかれさまです！
PlanetScale にて以下のご操作をお願いしたいと思っております。

- Branches > New branch からブランチを作成していただく (ブランチ名: staging)
- 作成したブランチにて Connect からユーザー名・パスワードを取得していただく
- 取得したユーザー名とパスワードを slack などにて共有していただく

また既に存在しているブランチと合わせて、両方とも production ブランチになっていないことのご確認もお願いできればと思います。
(特に操作していなければ、develop ブランチのままだとは思います)

お手すきの際にご確認をお願いできますでしょうか？
よろしくお願いいたします。

**Comment by muchoco-dev** [comment]
お疲れ様です！
staging ブランチ作成しました。
Slack にて共有済みです。

> また既に存在しているブランチと合わせて、両方とも production ブランチになっていないことのご確認もお願いできればと思います。
> (特に操作していなければ、develop ブランチのままだとは思います)

すみません、こちらがなんのことか理解できておりません。
PlanetScale のブランチは main と staging が存在しております。
![image](https://user-images.githubusercontent.com/16621023/229355613-3403c0e7-0740-466f-bd97-b17ea3e4eacb.png)



wake database

**Comment by HaruyaFujimoto** [comment]
@muchoco-dev 
おはやいご確認ありがとうございました！

すいません、ブランチの件は説明不足でした。。
画像を添付していただいたおかげで状況が確認できました。
その状態で大丈夫そうです、ありがとうございます！
