### ISSUE TITLE
一度2月中のスケジュールをざっと計画する

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#12]
2/10のリーダーMTで、2月中に各チーム準備完了～、という感じで大まかな目安が決まったので、それに合わせてある程度の計画を立てたい。
[【議事録】2023_02_10 チーム開発会議リーダーミーティング · commew/timelogger-lp Wiki](https://github.com/commew/timelogger-lp/wiki/%E3%80%90%E8%AD%B0%E4%BA%8B%E9%8C%B2%E3%80%912023_02_10-%E3%83%81%E3%83%BC%E3%83%A0%E9%96%8B%E7%99%BA%E4%BC%9A%E8%AD%B0%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC%E3%83%9F%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0#%E4%BB%8A%E5%BE%8C%E3%81%AE%E9%80%B2%E3%82%81%E6%96%B9)

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki おつかれさまです。

> 1をこのまま https://github.com/commew/timelogger-api/issues/9 https://github.com/commew/timelogger-api/issues/5 あたりでふじもとさんに続けてもらっていいでしょうか？

こちら承知しました。
今までに決まっている分で大丈夫な気がします。
むちょこさんに GCP のプロジェクト作成依頼 & 私と林さんへの権限付与依頼 (こちらの google アカウントをお伝えする)
があれば、本番デプロイ自動化の作業は進められそうだと思います。

> 2はcommittee-railsにするか、rswagにするかだけ決めたいところです。

こちらは、rswag が優先かなと思いました。
スキーマ自動生成の機能が欲しいことと、swagger-ui までついてくるのでフロントエンドチームに優しいかなと思いました。
そんな理由で、今回は rswag を使うということでいかがでしょうか？

**Comment by HAYASHI-Masayuki** [comment]
@HaruyaFujimoto ありがとうございます！　ではこの流れで進めましょう。
>  むちょこさんに GCP のプロジェクト作成依頼 & 私と林さんへの権限付与依頼 (こちらの google アカウントをお伝えする)

こちらもお願いしていいですか？　私のGoogleアカウントというかGmailアドレスは masayuki.hayashi.mcc@gmail.com です。

>  スキーマ自動生成の機能が欲しいことと、swagger-ui までついてくるのでフロントエンドチームに優しいかなと思いました。

なるほど。ではrswagで行きましょう！

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
メールアドレスありがとうございます！GCP の件は私のほうでむちょこさんに依頼してみます。

それでは 2 の方はよろしくお願いいたします！

別件なのですが、このリポジトリのブランチ保護やデフォルトブランチの設定など、私の方で変更しても大丈夫でしょうか？
もしくは林さんにお願いできたりしますでしょうか？

**Comment by HAYASHI-Masayuki** [comment]
@HaruyaFujimoto リポジトリの設定なんかも、変更していただいて大丈夫ですよー。
どこを設定したかはメモ程度でも残ってるとちょっと嬉しいかもしれません。

**Comment by HAYASHI-Masayuki** [comment]
2月中にやることは https://github.com/commew/timelogger-api/issues/12#issuecomment-1435439485 で決まったのでdone.
