### ISSUE TITLE
rubocopをどう運用していくか決める

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#18]
#16 の実装時に一回手動で動かしてみたが、自動生成ファイルも含めてかなり多くの警告？　が出ていた。
そもそも警告のレベルも私はよくわかっていないので、調べる必要がある。
現在のレベルのままで行くのか、調整するのか。
自動生成ファイルにも適用するのかしないのか。
自動化するのか。
などなど、決める。

**Comment by stkzk3110** [comment]
基本、最初は無理に全てにrubocopを適用する必要ないので、とりあえず以下とかの記事を参考にrubocop.ymlを修正してそこでエラーになるのを潰すなりymlを見直すなり一旦、修正を後回しにしたい場合、rubocop.todo.ymlを駆使して一時的に対象外とかにもできるのでまずなんかを参考にrubocop.ymlを設定しちゃうで良いと思います🙏

今の内容は見た感じ少ないので以下あたりを参考に追加すると良いかもです。
うちのプロダクトで使ってるのもあるのでその辺と照らし合わせてあったほうが良いとかのアドバイスもできそうです。

あと自動生成ファイルは、結構、対象外にしてたりしますね。

あとは本体コードだけじゃなくてRSpec側もrubocop設定できたりします。

参考：
https://blog.to-ko-s.com/rubocop-setting/
https://tandems.co.jp/blog/202212/1839733279

一旦、方針としては、とりあえず何かしら参考になる記事からベースのrubocop.ymlを作って流して一旦そこでコケたのは全部対象外とかにしておくと良いかもです。とりあえず新規コードにはそのルールが適用されるので既存コードは、後々メンテでもいいので。

参考になればと🙏

**Comment by HAYASHI-Masayuki** [comment]
ありがとうございます、参考になります！

- [ ] ある程度の指針を決める。
      @HaruyaFujimoto どういう感じがいいか、ご意見ください！　厳しめとかゆるめとか、todoベースでやるか最初にできるだけ潰してからやるか、など。
- [ ] rubocop-rspec調査・検討。

**Comment by HaruyaFujimoto** [comment]
個人的意見では割と厳しめでもいいのかも？と思っています。
rubocop の rails 向けの設定や gem があったり (rspec も同様) そうゆうものがあれば導入したいと思っています。

基本的には「こうゆう書き方をすると怒られるんだな〜、こうゆう書き方の方が推奨なんだな〜」という体験をして
望ましそうな記述を知れると嬉しいなと思っています。(これが一番の意見かもしれません)
どうにもならないときは、es-lint みたいに特定の行だけ対象外にすることもできるそうながするので
一度かっちりにしてみて「これはさすがに余計かも」と思えるルールに出会い次第、除外していく感じではどうでしょうか？

例えば、 @stkzk3110 さんが共有してくださったリンクにあった設定の

> \# 日本語にコメントを許可
> \# クラスにコメントを残さなくても良い
> \# 文字列のfreeze（Ruby3からは自動でfreezeされるので要らない）

こうゆうのはルールから除外しちゃってよさそうだなと思いました。

あとは Exclude 系の設定もかなり参考になりますね。
rswag で生成したようなファイルなども検査対象外にしてよいと思います。

私の意見としましては、ルール自体は厳しい分には割と大丈夫で逆に緩めでも特に問題はないです。
最近 es-lint にいじめられて耐性が少しついたので、まず怒られてみてからでいいのかなと思っています。

ここまではあくまで個人の意見で、チーム開発としては緩めの方が作業効率は良くなると思うので、
そのあたりは林さん個人はどういう感じで考えているかなどお伺いできると嬉しいです。

**Comment by HAYASHI-Masayuki** [comment]
さっそくありがとうございます！　私も厳し目にして、Rubyの人たちのベストプラクティスを知りたいので、厳し目で行ってみましょう！

* よさそうなベース設定があれば入れてみる(ちょっと探した感じあまりなさそうではあったが)。
* rubocop-rspecのような追加のライブラリもせっかくだし試してみる。
* とはいえ、日本語コメント禁止あたりは多分いらないのでオフにしてみる。
* 自動生成系は除外で。

という感じでやってみようと思います。
その辺の調整と、既存のコードへの反映をまた実装してPR出しますので、そのときはレビューお願いいます。

**Comment by HaruyaFujimoto** [comment]
承知しました！
では Rubocop まわりのところは一度林さんにお願いできればと思います！

**Comment by HAYASHI-Masayuki** [comment]
>  \# 文字列のfreeze（Ruby3からは自動でfreezeされるので要らない）

ちなみにRuby 3から文字列を自動でfreezeするのは、どうも廃案になったようです。

https://bugs.ruby-lang.org/issues/11473#note-53
