### ISSUE TITLE
環境ごとに定数を扱う方法を導入する

### ISSUE THREAD

**Issue by HaruyaFujimoto** [commew/timelogger-api#19]
#16 で必要性がはっきりしたので issue 化。
なんらかの方法で swag-ui にて扱う URL は環境ごとに切り替わるようにする必要がある。
少し調べてみて、以下のあたりが参考になりそうかなと思った。

参考リンク
- [Railsの環境変数の作成方法3パターン(config_for/global/config)比較 | Enjoy IT Life](https://nishinatoshiharu.com/rails-environment-variables-setting/)
- [【Ruby on Rails】 gem を使わないで環境毎に定数管理をする - きゃまなかのブログ](https://techblog.kyamanak.com/entry/2017/07/05/002655)

私の感想としては、

- config_for は参照する際の記述が長い
- https://rubygems.org/ で検索してみたところ、global よりも config の方が圧倒的に流行っていそう
  - config はだいたい 20M (回数)ダウンロード
  - global はだいたい 1M (回数)ダウンロード

というあたりから config の gem を導入するのがいいかなと思った。
また「自分で実装してみる」という選択肢は全然ありだと思うが、その場合は wiki などのしっかりドキュメント化する必要があることも
考える必要あり。

**Comment by HaruyaFujimoto** [comment]
もう少し考えてみたら、このプロジェクトにて管理するべき環境ごとの定数はそんなに多くなさそうかも？と思った。
その場合だと追加の gem を導入せずに config_for でもよさそうかもしれない。

- 定数を参照する記述が多くて、呼び出す際の記述量のコストを低くしたい場合は config を導入
- 定数を参照する箇所が限られていそうなら config_for

こんな感じで検討中で、今は config_for でもいいのかなと思っている。

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
おつかれさまです！
https://github.com/commew/timelogger-api/pull/16#discussion_r1118010527 こちらで必要性が出てきた
環境ごとの定数(変数)の扱い方について、少し調べて検討してみました。
この issue に関しまして、林さんのご意見を伺ってみたいと思っています。
お時間のあるときにご意見をお聞きできると嬉しいです！

**Comment by HAYASHI-Masayuki** [comment]
調査ありがとうございます！　私としても、

> もう少し考えてみたら、このプロジェクトにて管理するべき環境ごとの定数はそんなに多くなさそうかも？と思った。

こちらに同意なので、`config_for`を使う形で十分かなと思いました。
あと、参考ページの1つ目だと`config_for`を毎回使っているようですが、こちらを見た感じ、`config_for`は構成ファイルを最初に読み込むときに一回使い、その値を`config.x`以下に設定して、その後はそれを使っていく感じなのかなと思いました。この辺どうなんでしょうね？

https://guides.rubyonrails.org/configuring.html#custom-configuration

**Comment by HaruyaFujimoto** [comment]
rails のリポジトリで検索してみたらこんなテストコードが見つかりました。

https://github.com/rails/rails/blob/1797e5b67b8a673ffa9d69c72d90ff711a55582e/railties/test/application/configuration_test.rb#L2227
https://github.com/rails/rails/blob/1797e5b67b8a673ffa9d69c72d90ff711a55582e/railties/test/application/configuration_test.rb#L4464

こちらを見ると `config` に独自の参照名を追加して、そこへ `config_for` の返り値を代入して使うことを想定していそうだなと思いました。
ですので林さんのご指摘の通りのやり方がよさそうです！

**Comment by HaruyaFujimoto** [comment]
#17  に先に立ってた issue があった。
この issue は close する。
