### ISSUE TITLE
OpenAPIスキーマへの準拠性の確認にcommittee-railsを使うか検討する

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#28]
[rswagはもう不要なので削除する](https://github.com/commew/timelogger-api/issues/27)ので、spec -> OpenAPIスキーマという流れはなくなり、OpenAPIスキーマはフロントエンド側で実装されるものの、スキーマとAPI実装の乖離のチェックはなくなる。
これをたとえば[committee-rails](https://github.com/willnet/committee-rails)などを使って担保するか、ふつうにspecを書くかなど、検討する。

**Comment by HAYASHI-Masayuki** [comment]
committee-railsを使う場合、OpenAPIスキーマの参照をどうするかも要検討。
URL見られるならそうする？　でなければフロントエンド側をサブモジュールとして持つ？　これだけのためにそれはいやだなあ……。

**Comment by y-uchiida** [comment]
@HAYASHI-Masayuki 
サブモジュールとしてAPI仕様書のyaml だけ持ってくるのがよいのではないかと思いました！

公開された固定のURL上に常に最新のAPI仕様書があるなら、そのURLを参照するのでもよいかと思いましたが、、、
たしか、フロントでは開発サーバーなどをもたずコミットごとに一意なURLを持つということだったので、開発時に常に参照できるURLってないんじゃないかなと思いまして...
（フロントチームに確認したほうがよいかも）

ということから、sparse checkout で、yamlの入ってるディレクトリだけサブモジュールとして持つのがよい塩梅なのかなと思います。

**Comment by HAYASHI-Masayuki** [comment]
@y-uchiida 

ありがとうございます！　そうなんですよね、常に最新の仕様書が公開されているわけではないようなので。サブモジュールで検討してみようかと思います。

@keitakn 

詳しくご説明いただきありがとうございます！　timmew.commew.net のものはやはり常に最新とは限らないですよね。
今回はリポジトリ分けるほどではないし、分けるとあきらかに大変なので、サブモジュールにしてみようかと思います。

**Comment by HAYASHI-Masayuki** [comment]
なかなか時間も取れないので、一旦「ふつうにspecを書く」で。
