### ISSUE TITLE
RailsでREST APIする方法を調べる

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#3]
なにもわからないんでざっと調べておく。Grape使えばいいの？　使うまでもないの？

**Comment by HAYASHI-Masayuki** [comment]
2/10のリーダーMTで、keitaさんからGrapeいらないかも？　という話があったので、ちょっと調べてみた。
RailsでREST APIを実装していくには、大きく以下3パターンくらいありそう。

1. 普通にコントローラでJSONをレンダリングして返す。JSONどう生成するか、どうレンダリングするかはいろいろありそう？
2. RailsのAPIモードを使う。不要なビュー関連のGemとかが入らないとのこと。でもそれ以外は1と同様？
3. Grapeなどライブラリを使う。

で、あまりこの辺しっかり比較している人とか見ないので、結局自分で試さないとわからなそう。試す余裕がない場合、今回は1でもいいのかも。

API自体をどう作るかより、OpenAPIなドキュメントをどう生成するか、の方が大事かも。
とりあえずrswagとかいうライブラリを使えば、書いたテストを元に自動生成してくれる模様。
この辺一回試したい。

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
おつかれさまです！
リーダーMTおつかれさまでした。

私もこちらどうするかな〜とちょっと調べていて、API サーバーとしての機能自体は Rails の素の機能だけでよさそうかも？と考えていました。
ローカル環境構築の際に (2.) にあたる Rails の API モードで環境を立てたので、今は (2.) になっていそうです。

> API自体をどう作るかより、OpenAPIなドキュメントをどう生成するか、の方が大事かも。

こちらのために使える gem などを探していたのですが、rswag は良さそうですね！
定義ファイルの出力に、API 仕様を確認できる画面のルーティングまであって便利そうです。

私が調べていたときに committee-rails という gem を使うのが良さそうかなと考えていたのですが、
こちらはドキュメント生成ではなく、実装をした API が返す値が swagger で定義した通りになっているか、
をテストするのに使えそうな gem でした。
なので合わせて使うのもいいのかなと考えていました。

**Comment by HAYASHI-Masayuki** [comment]
ありがとうございます！

>  ローカル環境構築の際に (2.) にあたる Rails の API モードで環境を立てたので、今は (2.) になっていそうです。

なるほど……。よく見るとコミットログ内にしっかり書かれていました。
これはこのままAPIモードで進めるのがよさそうですね！

committee-railsもざっと見てみました。これはOpenAPIのスキーマを書くと、スキーマ通りの実装になっているか自動でテストできる、という感じのようです。
rswagはRSpecで書いたテストからスキーマを生成、のようなので、併用はなんか卵と鶏みたいな話になりそうで、できないかもしれません。
どちらも面白そうなので、どちらを使うかはふじもとさんにお任せします！

**Comment by HAYASHI-Masayuki** [comment]
* Grapeなどのライブラリは使わずに、RailsのAPIモードで書く。
* rswagを使って、OpenAPIのスキーマを生成する。

という方針で決まったのでこのissueはdone.
