### ISSUE TITLE
秘匿情報ファイルの保管・取り出し方法について検討

### ISSUE THREAD

**Issue by HaruyaFujimoto** [commew/timelogger-api#4]
これはフロントエンド側とも相談が必要かもしれない。

#1 はローカルで動く環境を作る、というところまでの環境構築だったが、環境変数などの管理が必要になる可能性が高そう。  
フロントエンド側で next-auth.js を使いたいというような話があがっていたので、jwt の復号のための鍵の管理も必要になるかもしれない。  

パブリックレポジトリ上において置けない情報の洗い出しと、保管方法、取り出し方法について決めておく必要がありそう。

rails にて .env の必要性が出てきたら、

- Dockerfile を書き直して dotenv-rails をグローバルにインストール
- README.md の修正
  - .env 等の習得手順の記載
  - 実行コマンドに dotenv を含めるようにする

等の対応を行おうかなと、今ところ考えている。

**Comment by HAYASHI-Masayuki** [comment]
ありがとうございます、確かに必要ですね。
デプロイどうやっていくか次第で要件や使える手段も変わってきそうなので、#5 共々進めていければなと思います。

**Comment by HaruyaFujimoto** [comment]
#6 にて少なくとも1つの .env で管理するべきものが具体的に見えたので、.env を扱える環境にするための issue を作成しようと思います。
このチケットでは秘匿情報の保管・共有方法、#5 に関連することについて引き続き検討できればと思います。

**Comment by HaruyaFujimoto** [comment]
#7 に追加の環境構築作業タスクを追加。

**Comment by keitakn** [comment]
こちらのissueの対応範囲はローカル開発環境だと思うのですが、本番ではCloud Runで実行するかと思いますので、その場合は[Secret Manager](https://cloud.google.com/secret-manager/docs?hl=ja#docs) を利用して実行中のコンテナに機密情報を渡す事が出来るのでそれを利用すると良いかと思われます。（GCP詳しくないですがおそらくAWSのFargate等と同じハズ・・・）

https://cloud.google.com/run/docs/configuring/secrets?hl=ja

**Comment by HAYASHI-Masayuki** [comment]
本当にいろいろありがとうございます。GCP側に置いておく手段があって、Cloud Runからはそれを使う形になるんですね。なるほど……。

**Comment by HaruyaFujimoto** [comment]
秘匿情報を共有できるようなストレージとして google drive を用意してもらった。  
現在 google drive に以下の情報を格納している。

- github secrets のキーバリュー
- DB 接続情報

**Comment by HAYASHI-Masayuki** [comment]
* Google Driveでとりあえず各人間で共有中。
* API側(こちらですね)のデプロイ時は、↑で共有のものをGitHub Secrets経由で使用している。

こんな状態という理解です。
API側でほかに考えることってありましたっけ。本番環境デプロイテストも成功されていますし、もうこのIssue閉じちゃってもいいのかも……？

**Comment by HaruyaFujimoto** [comment]
GCP の Secret Manager も使いつつ、暗号化した機密情報を git 管理化に含める方法を検討しています。
少し前ですが、2023-04-05 にミーティングをした際にきゅーぶさんに相談させていただき、
その方法でもよさそう〜というお話を少しさせていただきました。

参考 URL:
https://railsguides.jp/security.html?version=7.0#%E7%8B%AC%E8%87%AA%E3%81%AEcredential

具体的な情報管理方法としまして、暗号化するキーを

- 本番・検証環境では環境変数で管理
- ローカル開発環境では google drive 経由で共有

というように管理し、ローカル開発環境で機密情報を編集する際には

1. 暗号化するキーをローカルに設置
2. `rails credentials:edit ` コマンドで編集を行う

という手順になります。(より詳しくは README.md に追記します)

本番・検証環境では環境変数にて指定したキーを用いて、必要に応じて復号した情報を参照するようになります。
これをすることで、Secret Manager で管理する機密情報が少なくなり管理がしやすくなればと思っています。

**Comment by HAYASHI-Masayuki** [comment]
検討ありがとうございます！
`config/credentials.yml.enc`を使う方法は、安全性と利便性が両立できそうでいい方法だと思いました。
`config/master.key`はすでに`.gitignore`に入っていますし、普通に扱えば安全に管理できそうです！
