### ISSUE TITLE
タスクグループ一覧取得APIを実装する

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#42]
以下は初期値なのかデフォルト値なのか次第でデータベース回りの調整が必要なので、そこだけ確認。
**基本初期値として、アカウント作成時あたりに初期化する感じでいいかなとは思う。**
↑でOK.

参考
https://github.com/commew/timelogger-web/issues/49#issuecomment-1509852834

```json
{
  "groups": [
    {
      "id": 1,
      "name": "仕事",
      "categories": [
        {
          "id": 1,
          "name": "会議"
        },
        {
          "id": 2,
          "name": "資料作成"
        }
      ]
    },
    {
      "id": 2,
      "name": "学習",
      "categories": [
        {
          "id": 3,
          "name": "TOEIC"
        }
      ]
    },
    {
      "id": 3,
      "name": "趣味",
      "categories": [
        {
          "id": 4,
          "name": "散歩"
        },
        {
          "id": 5,
          "name": "読書"
        }
      ]
    },
    {
      "id": 4,
      "name": "グループ未分類",
      "categories": [
        {
          "id": 6,
          "name": "移動・外出"
        }
      ]
    }
  ]
}
```

**Comment by HaruyaFujimoto** [comment]
進捗として、account との関連部分の記述はコメントアウトしている前提で、
migration file と model の記述は一周目の実装は完了した。
これからコントローラ側、つまり実際のレスポンス周りの実装に進む。

また、ドラフトの PR を立てた。 #46

**Comment by HaruyaFujimoto** [comment]
進捗について。
```
{
  "groups": [
    {
      "id": 1,
      "name": "仕事",
      "categories": [
        {
          "id": 1,
          "name": "会議"
        },
        {
          "id": 2,
          "name": "資料作成"
        }
      ]
    }
  ]
}
```
この形式を返せるところまで実装完了。
account との紐づけがないため、とりあえず1つの TaskGroup とそれに紐づく TaskCategory を
返すところまでとしている。

あとは、

- [ ] account とのテーブル・モデルの関連付け
- [ ] アカウントごとに全種類の TaskGroup を作成する
- [ ] 今は返す json は TaskGroup のインスタンスの #as_json を呼んでいるが、account に紐づく複数の TaskGroup の情報を返す場合の実装を検討しておく

などが必要そう。

別件だが、ローカルでも PlanetScale を開発・テスト環境で動かせるように、
やはり dotenv を導入した方がよいかもしれないと思い始めた。

**Comment by HaruyaFujimoto** [comment]
異常系のレスポンスに関して、`ApplicationController` に記述していいのでは？と思い始めた。
GET: /task-groups のエンドポイントでは、想定されているレスポンスは、
200, 401, 500 で 401 は認証の部分で返すことになりそう。
500 エラーはどのエンドポイントでも使われうると思うので、共通処理として書いてよいのではと思った。
まだよく検討はしていない。

**Comment by HAYASHI-Masayuki** [comment]
@HaruyaFujimoto 
> 異常系のレスポンスに関して、ApplicationController に記述していいのでは？と思い始めた。

同意です！
401に関しては、JWTの共通実装で実装します。
500に関しては、このIssueで対応したいな……と思ってました。 https://github.com/commew/timelogger-api/issues/35

**Comment by HaruyaFujimoto** [comment]
承知しました！500 はすでに issue が立っていたのですね。

このエンドポイントは認証以外では異常系はない (リクエストパラメータがない)ので
この issue では正常系のレスポンスだけテストしておこうと思います！

**Comment by HaruyaFujimoto** [comment]
#46  での残りタスク

- [ ] テストの整理

これが済んだらドラフト外してレビュー依頼をします！

**Comment by HaruyaFujimoto** [comment]
ちなみに、相談なく FactoryBot を導入してしまいましたが、
そのときに参考にした公式のドキュメントらしきものです。
https://github.com/thoughtbot/factory_bot/blob/main/GETTING_STARTED.md

account, open_id_provider, task_groups の関連の状況で、
使いやすくて見やすい factory 書くために結構時間を使ってしまいました。

忘れていましたが、全てのモデルの factory を用意したほうがいいと思うので
TaskCategory の factory もささっと書く予定です。

**Comment by HAYASHI-Masayuki** [comment]
ありがとうございます！
FactoryBotの書き方さっぱりなので、レビューのときにしっかりコード読んで参考にさせていただきます。
