### ISSUE TITLE
本番デプロイをする (費用がかかるので先延ばしにしている)

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#5]
#4 とかなり関連しそうなので、いっしょにやった方がいいかも。
使用サービスとしては、

* Cloud Run (or?) さくらのVPS
* PlanetScale

らしい。そちらの調査・契約が先に必要そう。

**Comment by HaruyaFujimoto** [comment]
> Cloud Run (or?) さくらのVPS

こちらについて、個人的な意見としましては Cloud Run の方がデプロイ面は楽そうだなと思いました。  
CI/CD 構築しなくても gcloud-cli にてデプロイコマンドで手間もお金もお安く済みそうかなと思っています。

> PlanetScale
こちらに関しましては契約についてむちょこさんに相談・依頼する必要がありそうですね。

**Comment by muchoco-dev** [comment]
> PlanetScale

DB など作成時に必要な項目の内容が決まりましたら教えてください～！

**Comment by HAYASHI-Masayuki** [comment]
@HaruyaFujimoto ありがとうございます。

> CI/CD 構築しなくても gcloud-cli にてデプロイコマンドで手間もお金もお安く済みそうかなと思っています。

ちょっと私初回のMT出ていないのでどういう経緯でこの辺決まったのかわかってなかったんですが、やっぱり併用というわけではなく、Cloud RunならCloud Run単体で～、ということなんですね。であればCloud Runでよさそうですね。

@muchoco-dev お手数かけます、了解です。

**Comment by HaruyaFujimoto** [comment]
PlanetScale について、

- データベース名を決める
- aws リージョンか GCP か選ぶ、基本は aws の ap-northeast-1 ? (以下画像参照)

これだけ決められたらむちょこさんに依頼できるかなと思いました。

[![Image from Gyazo](https://i.gyazo.com/452cf60a3077f2521a33a82603286258.jpg)](https://gyazo.com/452cf60a3077f2521a33a82603286258)

フリープランで作れると思うので、コストとしてはいつ作成しても大丈夫かなと思います。

またDB作成後には Connect というボタンから以下の画像のような情報が取れますので、
slack などでそれの共有をお願いできればいいのかなと思います。
(下記の DB は削除済です！)

[![Image from Gyazo](https://i.gyazo.com/c82c41cd08c54f4cf22bae1f85105f18.png)](https://gyazo.com/c82c41cd08c54f4cf22bae1f85105f18)

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 

> データベース名どうしましょうね？　私はtimeloggerか、timelogger-api(そのまんまやん)くらいしか思い付かないですが。

`timelogger` でよさそうかなと思いました！
あるいは文字列としてなにを表すものかがわかるように `timelogger-db` とかでしょうか？
私はこんな感じで考えました。

> よく見るとGCPはBetaのようなので

そうなんですよね、開発中に Beta から正式対応に昇格してくれると嬉しいですね。
一旦は aws の tokyo でよさそうかなと私も思います！

**Comment by HAYASHI-Masayuki** [comment]
> あるいは文字列としてなにを表すものかがわかるように `timelogger-db` とかでしょうか？

なるほど！　これがいいと思います。

明日少し時間取れるので、もうちょっと確認してみて、むちょこさんに依頼してみます！

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
むちょこさんから接続情報をいただきました。
ご依頼ありがとうございました！

@muchoco-dev 
PlanetScale での DB 作成ありがとうございました！
接続確認も無事完了いたしました。

**Comment by HaruyaFujimoto** [comment]
となると次は GCP の方のプロジェクト作成や権限付与の依頼をする感じでしょうか？

- GCP にて新しいプロジェクトを作成していただく (プロジェクト名を決めてお伝えする？)
- 新しいプロジェクト内の IAM にてアクセス権の付与をお願いする (林さんと私の google アカウントのメールアドレスをお伝えする)
- IAM のロールは編集者にしてもらう (でよさそう？)

決め事はこのくらいかなと今のところ思っています。
GCP のことは依頼する前に、一旦前もって使用しそうなサービスの一覧と料金あたりの調査をしたいなと思っています。

**Comment by HAYASHI-Masayuki** [comment]
そうですね。なんとなくCloud RunとPlanetScaleだけでできるのかなー、と思ってたんですがほかにも必要なサービスありそうです？
IAMあまりわからないのでちょっと調べておきます！

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
#9 GCP 周りの話は一個の話題になりそうなので、issue を分けてみました！
一旦そちらでお話できればと思います。

**Comment by HaruyaFujimoto** [comment]
デプロイ自動化のための使用ツールやクラウド構成などはこちらで解決。
https://github.com/commew/timelogger-api/issues/9#issuecomment-1435492778

上記では API エンドポイントのドメイン名周りは考慮外としているので、そちらは後ほど検討・対応する必要あり。

**Comment by HaruyaFujimoto** [comment]
@muchoco-dev 
おつかれさまです！
今回 API 側のアプリケーション基盤となる GCP に関しまして、
むちょこさんにコンソール上で以下の操作を依頼したいと思っております。

1. GCP にて「新しいプロジェクトの作成」、プロジェクト名 "timelogger-api"
2. プロジェクトにて IAM の設定
  - アクセス権を付与 -> プリンシパルの追加 -> 下記のメールアドレスにて林さんと私の google アカウントにアクセス権を付与していただく
  - ロールを割り当てる -> クイックアクセス -> 基本 -> 編集者
  - 「新しいプリンシパル」のメールアドレス
    - 林さん
      - masayuki.hayashi.mcc@gmail.com 
    - 藤本
      - hal2cilu@gmail.com

ロールに関しましては、

- CloudRun
- Artifact Registry
- Secret Manager
- IAM

の管理権限があれば十分だと思うのですが、個別に権限を設定するのはけっこう手間かと思いますので、編集者権限にてお願いできればと思います。
不明瞭な点などありましたらコメントをいただければと思います。

お手すきの際に、ご確認をよろしくお願いいたします！

**Comment by muchoco-dev** [comment]
@HaruyaFujimoto 
気づくのが遅くなってすみません！
Slack でのご連絡ありがとうございました 🙇 
作成しましたのでお手すきでご確認をお願いします！

https://console.cloud.google.com/welcome?project=timelogger-api&hl=ja

**Comment by HaruyaFujimoto** [comment]
@muchoco-dev 
プロジェクトにて権限等確認ができました。
迅速に対応していただき、ありがとうございました！

**Comment by HaruyaFujimoto** [comment]
GCP の該当するプロジェクトにて、初回デプロイの手順を再確認した。

すると GCP にて Artifact Registry に保存されているイメージを参照するために必要な権限が、
以前デプロイの調査を行ったときと変わっている様子。
(`resourcemanager.projects.createBillingAssignment` の権限が必要というメッセージが出た)

私のアカウントの権限で見れない、またおそらくデプロイ用に用意したサービスアカウントにも権限を付与しないと
自動デプロイは動かないのではないかと思われる。

また用意されているロールでこの権限を持っているものは「オーナー」ロールだけの様子。
私のアカウント及びデプロイ用のサービスアカウントにオーナーのロールを付与するのはあまりしたくないので、
ロールを用意する必要があるのかもしれない。

(GCP のロールに詳しくないので、認識違いがあるかも)

**Comment by HAYASHI-Masayuki** [comment]
なんかやっかいそうなことになってますね……。
名前見た感じ、請求関係の権限っぽいので、請求回りの設定を別途行えば大丈夫になったりしないですかね？
でもその場合権限が必要～、みたいなエラーじゃなくて、請求の設定をしてください、ってエラーになるか。

**Comment by HAYASHI-Masayuki** [comment]
@HaruyaFujimoto おつかれさまです！　すごい！　公式ドキュメントにあったとは……。
最初のリンクの内容が原因だとすると、もしかしたらもう一回試したら通ったりしますかね？(そういうことではない？)

>  そのまま投げるとむちょこさんの負担になりそうなので情報整理をしたい。

これは確かにそうなんですが、今優先したいのはフロントエンド・バックエンド連携しての動作確認をできるだけ早くできるようにすることなので、現在までの情報でむちょこさんに確認お願いしたり、前ちょっと話したようにふじもとさんのアカウントで動作確認できるようにしたりする方向もありかと思います！

**Comment by HaruyaFujimoto** [comment]
@HAYASHI-Masayuki 
ご確認ありがとうございます！
情報整理と言っても伝える文言を整理するくらいの意味でしたので、今日には連絡しようと思っています！

**Comment by HaruyaFujimoto** [comment]
@muchoco-dev 
おつかれさまです！
バックエンド側のデプロイ作業にあたり、むちょこさんにお願いしたいことが出てきたためご連絡させていただきます。
お手好きの際に以下の2点のご確認をお願いできますでしょうか？

1. PlanetScale にて用意していただいた DB がスリープしているかと思いますので、復帰をお願いしたいです
2. GCP の該当するプロジェクトにて、課金の設定の確認をお願いしたいです
  - しばらくプロジェクトを触っていなかったためか、料金の発生するサービスを使用しようとした際に
    課金に関する権限のエラーが出るようになってしまったため、この依頼をする必要が出てきました
  - 参考リンク
    - https://cloud.google.com/billing/docs/how-to/modify-project?hl=ja#how-to-enable-billing
    - https://cloud.google.com/billing/docs/how-to/modify-project?hl=ja#enable_billing_for_an_existing_project

ご確認をよろしくお願いいたします！

**Comment by muchoco-dev** [comment]
@HaruyaFujimoto 

お疲れ様です！
ご連絡ありがとうございました。

> PlanetScale にて用意していただいた DB がスリープしているかと思いますので、復帰をお願いしたいです

今起こしました。少し経ったら使えるようになると思います。

> GCP の該当するプロジェクトにて、課金の設定の確認をお願いしたいです

無料期間が終わっていたみたいですね。課金設定しました。

それぞれもししばらく経ってもまだ使えないようでしたら、お手数ですが再度ご連絡いただけますと幸いです。
よろしくお願いします！

**Comment by HaruyaFujimoto** [comment]
@muchoco-dev 
ご対応ありがとうございました！
DB と GCP のプロジェクト、両方とも動くことを確認しました！

**Comment by HaruyaFujimoto** [comment]
本番への初回デプロイ完了。
close #23 

DB の migration も実行し、curl を使って最低限の動作確認も完了。
CloudRun で自動的に割り当てられるホスト名を DNS へ登録してもらう依頼を検討する。

また検証環境はまだ立てていないが、PlanetScale の検証用のブランチにて
migration 実行時にエラーが出ることを確認。

`Mysql2::Error: held locks released:`

PlanetScale のここの制約に引っかかって20秒以上かかる transaction でエラーが出ている様子。
https://planetscale.com/docs/reference/planetscale-system-limits#query-limits

production, staging それぞれのための DB のブランチにて migration を実行した際に、
staging の方が実行時間がだいぶ長かったのが少し気になる。

とりあえずこの issue の残りタスクとしては、デプロイした CloudRun に
フロントエンドと同じドメインのサブドメインを割り当ててもらうよう依頼すること。

**Comment by HAYASHI-Masayuki** [comment]
@HaruyaFujimoto おつかれさまでした！
>  CloudRun で自動的に割り当てられるホスト名を DNS へ登録してもらう依頼を検討する。

これどうしましょうね？　先週話しましたが、バックで動くだけなので名前なくてもいい気はします。
フロントエンドとの連携のために、またURL共有していただけると助かります！
って私が知らないだけでURLはもう共有されてるんでしたっけ……？

> `Mysql2::Error: held locks released:`
> 
> PlanetScale のここの制約に引っかかって20秒以上かかる transaction でエラーが出ている様子。

これってどれくらい影響ある感じでしょう？
初期デプロイには問題ないけど、その後のデプロイで問題ありそうな感じなんでしょうか？
ちょっと気になりますね。またIssue作っておいた方がよさそうです。

**Comment by HaruyaFujimoto** [comment]
> フロントエンドとの連携のために、またURL共有していただけると助かります！

slack にて URL の共有をさせていただきました。
ご確認をお願いできればと思います！

> これってどれくらい影響ある感じでしょう？

ちょっと触ってみたのですが、staging で使用している DB は migration に限らずなんのクエリでもけっこう遅い気がします。

ローカル開発環境の docker コンテナに入り、`bin/rails console --environment=staging` でお試しいただけます。
私の方で上記の方法でコンソールを開き `Account.count` を実行したところ、それだけでも少し時間がかかっていました。
ですので、デプロイだけじゃなくアプリの動作で問題が出なければいいな、と考えていました。

この辺は実際に検証環境を運用してみて、問題になるようであれば DB を他の手段で用意する方法を考える
という感じはどうかなとなんとなく考えていました。

そんな感じでもよさそうでしょうか？

**Comment by HAYASHI-Masayuki** [comment]
ありがとうございます！

> ローカル開発環境の docker コンテナに入り、bin/rails console --environment=staging でお試しいただけます。
> 私の方で上記の方法でコンソールを開き Account.count を実行したところ、それだけでも少し時間がかかっていました。

なるほど……。私はデプロイさえ通れば、検証時に多少遅いのは別にいいかなー、という感じですね。
で、私の手もとでも`rails c`でステージングつないで試してみましたが、最初の接続こそ遅かったものの、その後は特に遅くなさそうでした。それも含め、

> この辺は実際に検証環境を運用してみて、問題になるようであれば DB を他の手段で用意する方法を考える

これでなんの問題もないと思います！

しかしローカルの開発環境から直接PlanetScaleつなげる体験は面白いですね。

**Comment by HaruyaFujimoto** [comment]
> これでなんの問題もないと思います！

ご確認ありがとうございます！
ではそんな感じで進められたらと思います。

ローカル環境にて credentials の .key ファイルを持っておくとこれができてしまうので、
実務であれば扱い要注意ですね。。
shell の履歴で間違って実行したりしたら大変です。。

確認いただけたのでこの issue は閉じます！
