### ISSUE TITLE
NextAuth.js の仕様の調査

### ISSUE THREAD

**Issue by HaruyaFujimoto** [commew/timelogger-api#6]
フロントエンド側で SaaS を使ったログイン管理をしたいとのことだったので、その場合に API 側でどんな実装が必要になるか調査。  
軽い話として jwt をつけてリクエストする、といったことを聞いた気がするが、その jwt 自体はこちらの API ではない場所で作成されるかのような話に聞こえた。  
その辺よくわかってないので、まずは NextAuth.js の仕様・機能の調査。  
API 側での実装方針については、仕様調査後に別の issue を立てる予定。

**Comment by HaruyaFujimoto** [comment]
デフォルトでの暗号化のアルゴリズム。
参考: [https://next-auth.js.org/faq#json-web-tokens](https://next-auth.js.org/faq#json-web-tokens)

> Does NextAuth.js use JSON Web Tokens?
...
> Since v4 all our JWT tokens are now encrypted by default with A256GCM.

**Comment by HaruyaFujimoto** [comment]
参考: [next-auth-example のプロジェクト内ソース](https://github.com/nextauthjs/next-auth-example/blob/8b5b2e113c1c12cba1092f9bf11652731f60b549/pages/api/auth/%5B...nextauth%5D.ts#L32)

>
```
    FacebookProvider({
      clientId: process.env.FACEBOOK_ID,
      clientSecret: process.env.FACEBOOK_SECRET,
    }),
```
この `process.env.FACEBOOK_SECRET` が jwt のシグニチャ部分を生成の際に使用するシークレットの様子。
参考 URL の周辺コードを見ると、OAuth プロバイダごとに別々の secret を設定する様子に見える。
これらの secret をフロントエンドとバックエンドで共通で持つ必要がありそう。
(#4 に関わりそう)

また jwt のペイロードの中で
```
{
  "oauth_provider": "Google"
}
```
みたいな情報も含めてもらわないと、API 側で復号するときにどの secret を使ったら良いか判別できない気がする。

**Comment by HAYASHI-Masayuki** [comment]
私もまだよくわかってないのですが、共有する必要があるのは https://next-auth.js.org/configuration/options#secret くらいだけじゃないかと思います。
`FacebookProvider`に渡しているのは、Facebook側のAPI用のトークンとかで、JWTには関係ないのではないかと。
で、バックエンドからはどこの認証プロバイダ経由で認証していても関係ないので、そちらも大丈夫な気がしてます。

@keitakn すみません、私こんなあやふやな理解しかないんですが、合ってますでしょうか……？

**Comment by keitakn** [comment]
@HAYASHI-Masayuki 

https://github.com/commew/timelogger-api/issues/6#issuecomment-1408444298

こちらで合っております！

APIの認証に関しては `Authorization` ヘッダーにJWTトークンを付けてリクエストするので、その中身を検証して頂き、正常であればリクエストを通して頂くという形になるかと思います。

どのプロバイダ（Google、　Facebook, etc）で認証したかについてですが、初期リリースでは必要ないと思います。

ですが今後、複数のプロバイダで登録が可能になると、Myページなどから別のプロバイダの紐付けを行う機能などを実装する場合はフロント側からどのプロバイダで認証したかの情報をバックエンドに伝える必要が出てくると思います。

※以下はQiitaのMyページで1つのQiitaアカウントにGitHub、Twitter、Googleなどの複数のプロバイダの紐付けが可能になっています。

![スクリーンショット 2023-01-30 23 11 48](https://user-images.githubusercontent.com/11032365/215500540-1429f378-1388-436f-a536-3837bfebd962.png)

どちらにせよ、https://github.com/commew/timelogger-web/issues/13 が終わった段階でこちらから必要な情報を改めて提供させて頂きます。

**Comment by HaruyaFujimoto** [comment]
ご確認ありがとうございます。
確かに、 https://github.com/commew/timelogger-api/issues/6#issuecomment-1408444298 こちらの通りですね！

> どのプロバイダ（Google、　Facebook, etc）で認証したかについてですが、初期リリースでは必要ないと思います。

> ですが今後、複数のプロバイダで登録が可能になると、Myページなどから別のプロバイダの紐付けを行う機能などを実装する場合はフロント側からどのプロバイダで認証したかの情報をバックエンドに伝える必要が出てくると思います。

> どちらにせよ、https://github.com/commew/timelogger-web/issues/13 が終わった段階でこちらから必要な情報を改めて提供させて頂きます。

こちらも共有いただきありがとうございます。
@HAYASHI-Masayuki さん、@keitakn さんにご確認いただいて仕様は理解できましたので、こちらの issue は完了としたいと思います。
お二人ともありがとうございました！
