### ISSUE TITLE
タスクからタスク時間へのリレーション名は複数形にしたい

### ISSUE THREAD

**Issue by HAYASHI-Masayuki** [commew/timelogger-api#61]
[こちら](https://github.com/commew/timelogger-api/blob/c2bf4fadec3ef863147934484a6eaaa6c5143396/app/models/task.rb#L3)単数形になっていてちょっと違和感あるので複数形に修正したい。

@HaruyaFujimoto すみません、こちらレビューで見落としてました。
OKであれば私の方でぱぱっと直します。意図的なものでしたら、相談しましょう。

**Comment by HaruyaFujimoto** [comment]
すいません、脳死で書いていたのでただのミスです。
直していただけるということであればお願いしたいです。
