### ISSUE TITLE
クラウド構成を検討する

### ISSUE THREAD

**Issue by HaruyaFujimoto** [commew/timelogger-api#9]
#5 こちらからの派生タスク。

アプリケーションを GCP の Cloud Run で動かすことと、DB として PlanetScale を使用することは決定している。
(PlanetScale については環境構築も済み)
他に GCP のサービスで利用するものがあるか、それぞれの役割はなにかを調査。
[Diagrams.net](https://app.diagrams.net/) などでクラウド構成図まで描ければなおよし。

それを元にデプロイの経路なども変わると思うので、クラウド構成の話はこちらで進めたい。

DNS 周りについてはここで話すかは微妙なところ。
フロント側の vercel で使いたいものがあったりするかもしれないので、DNS は一旦考えないものとする。

**Comment by HaruyaFujimoto** [comment]
とりあえず GCP で使用が確定しているものとして

- Cloud Run (アプリケーション実行環境)
- Artifact Registry (コンテナイメージの保管先)
- Cloud Build (コンテナイメージをビルドして Artifact Registry に保存してくれる。ビルド環境が変わるとイメージが変わるので必須そう)
- Secret Manager (秘匿情報の保管、Cloud Run や Cloud Build に秘匿情報を渡せる)

今の所こんな感じでしょうか。
あとは IAM での、 GCP のコンソールや cli の操作のためのユーザーの招待・権限付与、もですね。
今の所の認識はこんな感じです！

**Comment by HAYASHI-Masayuki** [comment]
検討ありがとうございます。私の方でもちょっと調べてみましたが、この辺すごくややこしいですね、難しいです……。
この辺の技術選定お任せしてしまっていいですか？
なんかGitHub ActionsとCloud Runだけで行けるかなー、と思ってたんですが。ほんといろいろありますね。

**Comment by HAYASHI-Masayuki** [comment]
IAMのロールは編集者でよさそうですね。もしサービスごとに編集者でできなくて、追加で必要な権限があれば、都度追加してもらう感じで。
後は料金回りですね。Cloud Runはおそらく一先ずは無料枠で行けるのかな……という感じですが、ほかのサービスがまだ見れてないです。ちょこちょこ見てみます。

**Comment by HaruyaFujimoto** [comment]
[Cloud Build を使用した Git からの継続的なデプロイ](https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build?hl=ja)
ここを見て上記のサービスが必要なのかな？と考えていました。
私も github actions がどこまでやってくれるサービスなのかあまり把握していなくて、Cloud Run のデプロイの項目に書いてある通りにしたらいいのかな？って感じで考えていました。

> この辺の技術選定お任せしてしまっていいですか？

一旦私の方で調査してまとめてみて、それを一度相談させてもらえると嬉しいです！

**Comment by HAYASHI-Masayuki** [comment]
なるほど！　多分これどっちでもできるし、なんならほかの手段でも……という感じっぽいですね。
GitHub ActionsでDockerのビルドは多分できるはずなんで、そうした場合はCloud Buildはスキップできると思います。
おそらくこの辺、それぞれのサービスの料金とか、連携しやすさとか考えて選択しないといけないんでしょうね。なかなか大変です……。

> 一旦私の方で調査してまとめてみて、それを一度相談させてもらえると嬉しいです！

もちろんです！　とても助かります！

**Comment by HaruyaFujimoto** [comment]
調べてみたところ、github actions は `「public レポジトリだと無料」` だと書いてあって無制限に料金がかからない様子です。
ですので今回のプロジェクトでのデプロイ用のコンテナイメージのビルドは、github actions のマシンリソースを使って行うのがよさそうかなと思いました。

private リポジトリを使っていてデプロイも頻繁、とかの要件であれば Cloud Build も十分検討しがいがありそうなのですが、今回は料金面で github actions でできうることは全部やるのがよさそうだと思いました。

他の利用する GCP のサービスは変わらずで、デプロイはこんな想定です。

```
## github actions で以下の job を行う
1. コンテナイメージをビルドする
2. Artifact Registry にコンテナイメージを push する
3. Cloud Run にデプロイを行う
```

(2.) と (3.) は gcloud-cli のコマンドを使って実行する感じです。

(2.) の Artifact Registry の料金について、少し料金が発生しそうだなと思っています。
料金は以下のようでした。
[参考url](https://cloud.google.com/artifact-registry/pricing?hl=ja)

Usage | 料金（GB 単位/月）
-- | --
最大 0.5 GB | 無料
0.5 GB 超 | $0.10

今のローカル開発環境用のイメージが0.5GBを超えているので、もしかしたら無料の枠を超えるかもな、という感じです。

調べたことと考えてみたことは以上でした。
なにか気になるところやよい情報などあれば、教えていただけると嬉しいです。

**Comment by HAYASHI-Masayuki** [comment]
詳しい調査ありがとうございます！　publicリポジトリだとGitHub Actions完全に無料なんですね。
Artifact RegistryはGitHub Actionsを使ってもなくせないんですね、なるほど……。

一応、おそらく同様のサービスっぽいGitHub Container Registryというものがあって、これが公開してよいコンテナイメージであれば、無料で使えそうなんですが、この場合ビルドした後のイメージって安全ですかね？
感覚的には、本当に公開できない情報は最後Cloud Runからコンテナを立ち上げる際に注入するので、なんか行けるかも……と思ったのですが。
https://docs.github.com/ja/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by HaruyaFujimoto** [comment]
## 料金について

> 同様のサービスっぽいGitHub Container Registryというものがあって、

github にも同様のサービスがあるんですね、知らなかったです！github 本当にすごい。。
軽く調べた感じですが、Artifact Registry はやはり使用する必要がある様子でした。

参考リンク
- [Cloud Run | サポートされているコンテナ レジストリとイメージ](https://cloud.google.com/run/docs/deploying?hl=ja#images)
- [Cloud Run | サポートされていないレジストリからイメージをデプロイする](https://cloud.google.com/run/docs/deploying?hl=ja#other-registries)

もしこのプロジェクトで Github Container Registry を使う場合に該当しそうな説明部分を以下にまるっと引用します。

> サポートされていない公開コンテナまたは非公開のコンテナ レジストリにコンテナ イメージを保存しているときに、イメージを Cloud Run にデプロイするには、docker push を使用して [Artifact Registry](https://cloud.google.com/artifact-registry/docs/overview?hl=ja) にイメージを一時的に push します。コンテナ イメージはデプロイ時に Cloud Run によってインポートされます。デプロイ後は、[Artifact Registry からイメージを削除できます。](https://cloud.google.com/artifact-registry/docs/docker/manage-images?hl=ja#deleting_images)

上記の引用から Artifact Registry を経由する必要がやはりありそうです。
他にわかったこととして、デプロイ後に Artifact Registry からイメージを削除すれば、デプロイを実行した月だけストレージ利用の料金が発生しそうです。
デプロイ自動化のフローに Artifact Registry 上のイメージ削除まで含めることになりそうだなと思いました。

[Artifact Registry | 料金](https://cloud.google.com/artifact-registry/pricing?hl=ja) にて、

>ストレージ料金は、Artifact Registry リポジトリ内にアーティファクトを保存する時点で適用されます。

とあるので、一時的にイメージを置いてすぐ削除をしても料金はかかりそうです。

## コンテナがもし公開されても安全かどうかについて

> これが公開してよいコンテナイメージであれば

コンテナイメージをビルドするための要素に github の secret を使用しないように注意すれば、そこの懸念はなくなりそうかなと思います。

- github-actions で実行するコマンドでのみ github の secret を使用 (gcloud-cli のコマンド実行の引数に使う)
- コンテナイメージ (Dockerfile 内の記述) では GCP の secret manager の情報だけを参照する構造にする

これをしておけばもしコンテナが公開されるような状況になっても大丈夫かなと思います。
Artifact Registry 方のアクセス権限周りもまだ完全には調べられていないので、公開されてもいい前提でコンテナイメージのビルドができたらいいなと思います。

**Comment by HAYASHI-Masayuki** [comment]
なるほど。似たようなものなら使えるのかなと思ったんですが、そうでもないんですね。

> サポートされているコンテナ レジストリとイメージ
> Container Registry または Artifact Registry に保存されているコンテナ イメージを使用できます。

* Artifact Registry使用は確定。
* 料金はかかるけど、デプロイ後にイメージを削除する設計にしておけば、デプロイしない月は無料で済みそう。

という感じですかね。

>  Artifact Registry 方のアクセス権限周りもまだ完全には調べられていないので、公開されてもいい前提でコンテナイメージのビルドができたらいいなと思います。

ですね！　公開する必要はなさそうですが、いずれにしても必要最小限の情報だけ持たせるのが安全ですよね。

**Comment by HaruyaFujimoto** [comment]
デプロイ自動化のための、クラウド構成の整理。
このタスクはこれで完了とする。
以下の情報で #5 を進める。

```
## デプロイ周りの構成
- デプロイ自動化ツール
  - github actions
    - gcloud-cli を使用する際の認証に必要な情報のため、github の secrets を使用する
- アプリケーション基盤
  - GCP
    - Artifact Registry
    - Cloud Run
    - Secret Manager (コンテナ内の機密情報を扱う)

## 今回考慮外となっている事
- エンドポイントのドメイン名やサーバー証明書等のためのリソース

## アクションリスト
- GCP 使用のための準備
  - むちょこさんへの依頼
    - GCP にてプロジェクト作成
    - IAM の設定依頼
- 本番・検証デプロイ用の Dockerfile の作成
  - 特に特別なことはなし
  - Cloud Run はデフォルトでは port 8080 を使用、コンテナで 8080 を listen する設定にする
  - コンテナイメージが小さいほどよいが、限度があるのであまりこだわらない
  - GCP Secret Manager の扱いを検討 (ボリュームとしてマウント、を使用するのがよさそう？)
- github actions の設定
  - トリガーを決める
  - job の中で gcloud-cli を使えるようにする
  - 現在は検証環境のことは考えず、以下のフローとする
    - テスト (今はスキップでいいかも)
    - ビルド (github actions でコンテナイメージをビルド)
    - コンテナイメージを Artifact Registry へ push
    - Cloud Run へデプロイ
    - Artifact Registry からコンテナイメージを削除
```
